SIM          = ghdl
TOPLEVEL_LANG = vhdl
VHDL_SOURCES  = $(PWD)/parallel_register.vhd
TOPLEVEL      = reg8
MODULE        = test_parallel_register

include $(shell cocotb-config --makefiles)/Makefile.sim