name: RTL Simulation - uart_rx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  simulate:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install GHDL
      shell: bash
      run: sudo apt install -y ghdl

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: rtl
        auto-activate-base: false

    - name: Run Top Level tests
      run: make -C uart_rx